# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: grafana-oidc-client-secret
# spec:
#   secretStoreRef:
#     name: k8s-vault-store
#     kind: ClusterSecretStore
#   data:
#     - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
#       remoteRef:
#         key: oidc
#         property: grafana-client-secret